package scripts.Miner;

import org.tribot.api2007.Player;
import org.tribot.api2007.types.RSArea;
import org.tribot.api2007.types.RSTile;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.FocusEvent;

/**
 *
 * @author James
 */
public class GUI extends JFrame {

    /**
     * Creates new form GUI
     */
    public boolean guiCompleted = false;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Z3D's AIO Miner");

        title_Lbl = new javax.swing.JLabel();
        rockArea_Panel = new javax.swing.JPanel();
        rockAreaTL_TxtBox = new javax.swing.JTextField();
        rockAreaBR_TxtBox = new javax.swing.JTextField();
        rockAreaTL_Btn = new javax.swing.JButton();
        rockAreaBR_Btn = new javax.swing.JButton();
        bankArea_Panel = new javax.swing.JPanel();
        bankAreaTL_TxtBox = new javax.swing.JTextField();
        bankAreaBR_TxtBox = new javax.swing.JTextField();
        bankAreaTL_Btn = new javax.swing.JButton();
        bankAreaBR_Btn = new javax.swing.JButton();
        bankTile_TxtBox = new javax.swing.JTextField();
        bankTile_Btn = new javax.swing.JButton();
        loadTilles_Panel = new javax.swing.JPanel();
        dataString_TxtBox = new javax.swing.JTextField();
        generateData_Btn = new javax.swing.JButton();
        loadData_Btn = new javax.swing.JButton();
        start_Btn = new javax.swing.JButton();
        rockName_Panel = new javax.swing.JPanel();
        rockIDs_TxtBox = new javax.swing.JTextField();
        options_Panel = new javax.swing.JPanel();
        bankOre_CheckBox = new javax.swing.JCheckBox();
        upgradePickaxe_CheckBox = new javax.swing.JCheckBox();
        autoHop_CheckBox = new javax.swing.JCheckBox();

        title_Lbl.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        title_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Lbl.setText("Z3D's AIO Miner");

        rockArea_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Rock Area"));
        rockArea_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockArea_Panel.setName(""); // NOI18N

        rockAreaTL_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockAreaTL_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rockAreaTL_TxtBox.setText("Top Left Tile");
        rockAreaTL_TxtBox.setToolTipText("The top left tile in the area in the format: 3897, 1089");
        rockAreaTL_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rockAreaTL_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rockAreaTL_TxtBoxFocusLost(evt);
            }
        });

        rockAreaBR_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockAreaBR_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rockAreaBR_TxtBox.setText("Bottom Right");
        rockAreaBR_TxtBox.setToolTipText("The bottom right tile in the area in the format: 3897, 1089");
        rockAreaBR_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rockAreaBR_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                rockAreaBR_TxtBoxFocusLost(evt);
            }
        });

        rockAreaTL_Btn.setBackground(new java.awt.Color(255, 228, 255));
        rockAreaTL_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockAreaTL_Btn.setText("Grab Tile");
        rockAreaTL_Btn.setToolTipText("Grabs the current tile you're standing on");
        rockAreaTL_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockAreaTL_BtnActionPerformed(evt);
            }
        });

        rockAreaBR_Btn.setBackground(new java.awt.Color(255, 228, 255));
        rockAreaBR_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockAreaBR_Btn.setText("Grab Tile");
        rockAreaBR_Btn.setToolTipText("Grabs the current tile you're standing on");
        rockAreaBR_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rockAreaBR_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rockArea_PanelLayout = new javax.swing.GroupLayout(rockArea_Panel);
        rockArea_Panel.setLayout(rockArea_PanelLayout);
        rockArea_PanelLayout.setHorizontalGroup(
                rockArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rockArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(rockArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(rockArea_PanelLayout.createSequentialGroup()
                                                .addComponent(rockAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rockAreaTL_Btn))
                                        .addGroup(rockArea_PanelLayout.createSequentialGroup()
                                                .addComponent(rockAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(rockAreaBR_Btn)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rockArea_PanelLayout.setVerticalGroup(
                rockArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rockArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(rockArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rockAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rockAreaTL_Btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(rockArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(rockAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(rockAreaBR_Btn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bankArea_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bank Area"));
        bankArea_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankArea_Panel.setName(""); // NOI18N

        bankAreaTL_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaTL_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankAreaTL_TxtBox.setText("Top Left Tile");
        bankAreaTL_TxtBox.setToolTipText("The top left tile in the area in the format: 3897, 1089");
        bankAreaTL_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankAreaTL_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAreaTL_TxtBoxFocusLost(evt);
            }
        });

        bankAreaBR_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaBR_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankAreaBR_TxtBox.setText("Bottom Right");
        bankAreaBR_TxtBox.setToolTipText("The bottom right tile in the area in the format: 3897, 1089");
        bankAreaBR_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankAreaBR_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAreaBR_TxtBoxFocusLost(evt);
            }
        });

        bankAreaTL_Btn.setBackground(new java.awt.Color(255, 228, 255));
        bankAreaTL_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaTL_Btn.setText("Grab Tile");
        bankAreaTL_Btn.setToolTipText("Grabs the current tile you're standing on");
        bankAreaTL_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankAreaTL_BtnActionPerformed(evt);
            }
        });

        bankAreaBR_Btn.setBackground(new java.awt.Color(255, 228, 255));
        bankAreaBR_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaBR_Btn.setText("Grab Tile");
        bankAreaBR_Btn.setToolTipText("Grabs the current tile you're standing on");
        bankAreaBR_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankAreaBR_BtnActionPerformed(evt);
            }
        });

        bankTile_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankTile_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankTile_TxtBox.setText("Centre Tile");
        bankTile_TxtBox.setToolTipText("A tile closest to the bank booth");
        bankTile_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankTile_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankTile_TxtBoxFocusLost(evt);
            }
        });

        bankTile_Btn.setBackground(new java.awt.Color(255, 228, 255));
        bankTile_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankTile_Btn.setText("Grab Tile");
        bankTile_Btn.setToolTipText("Grabs the current tile you're standing on");
        bankTile_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTile_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bankArea_PanelLayout = new javax.swing.GroupLayout(bankArea_Panel);
        bankArea_Panel.setLayout(bankArea_PanelLayout);
        bankArea_PanelLayout.setHorizontalGroup(
                bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                                .addComponent(bankAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bankAreaTL_Btn))
                                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                                .addComponent(bankAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bankAreaBR_Btn))
                                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                                .addComponent(bankTile_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bankTile_Btn)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        bankArea_PanelLayout.setVerticalGroup(
                bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bankAreaTL_Btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bankAreaBR_Btn))
                                .addGap(18, 18, 18)
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankTile_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bankTile_Btn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadTilles_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Load Tiles"));
        loadTilles_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loadTilles_Panel.setName(""); // NOI18N

        dataString_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        dataString_TxtBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dataString_TxtBox.setText("GUI Data String");
        dataString_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataString_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataString_TxtBoxFocusLost(evt);
            }
        });

        generateData_Btn.setBackground(new java.awt.Color(255, 228, 255));
        generateData_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        generateData_Btn.setText("Generate");
        generateData_Btn.setToolTipText("Generates a GUI data string");
        generateData_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateData_BtnActionPerformed(evt);
            }
        });

        loadData_Btn.setBackground(new java.awt.Color(255, 228, 255));
        loadData_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loadData_Btn.setText("Load");
        loadData_Btn.setToolTipText("Loads all GUI data from the Data String");
        loadData_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadData_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadTilles_PanelLayout = new javax.swing.GroupLayout(loadTilles_Panel);
        loadTilles_Panel.setLayout(loadTilles_PanelLayout);
        loadTilles_PanelLayout.setHorizontalGroup(
                loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loadTilles_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dataString_TxtBox)
                                        .addGroup(loadTilles_PanelLayout.createSequentialGroup()
                                                .addComponent(loadData_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(generateData_Btn)))
                                .addContainerGap())
        );
        loadTilles_PanelLayout.setVerticalGroup(
                loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loadTilles_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dataString_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loadData_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generateData_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        start_Btn.setBackground(new java.awt.Color(231, 234, 183));
        start_Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        start_Btn.setText("Start");
        start_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_BtnActionPerformed(evt);
            }
        });

        rockName_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Rock IDs"));
        rockName_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockName_Panel.setName(""); // NOI18N

        rockIDs_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        rockIDs_TxtBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        rockIDs_TxtBox.setToolTipText("All rock ID's 'Debug -> Objects -> Interactive Objects'");

        javax.swing.GroupLayout rockName_PanelLayout = new javax.swing.GroupLayout(rockName_Panel);
        rockName_Panel.setLayout(rockName_PanelLayout);
        rockName_PanelLayout.setHorizontalGroup(
                rockName_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(rockName_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(rockIDs_TxtBox)
                                .addContainerGap())
        );
        rockName_PanelLayout.setVerticalGroup(
                rockName_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rockName_PanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rockIDs_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        options_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Other Options"));
        options_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        options_Panel.setName("Options Panel"); // NOI18N

        bankOre_CheckBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankOre_CheckBox.setSelected(true);
        bankOre_CheckBox.setText("Bank Ore");
        bankOre_CheckBox.setToolTipText("If not checked will drop the ore");
        bankOre_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bankOre_CheckBoxItemStateChanged(evt);
            }
        });

        upgradePickaxe_CheckBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        upgradePickaxe_CheckBox.setSelected(true);
        upgradePickaxe_CheckBox.setText("Auto Upgrade Pickaxe");
        upgradePickaxe_CheckBox.setToolTipText("Will automatically get the best pickaxe from your bank and use that");

        autoHop_CheckBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        autoHop_CheckBox.setText("Auto Hop Worlds");
        autoHop_CheckBox.setToolTipText("Will hop worls if no rocks found");

        javax.swing.GroupLayout options_PanelLayout = new javax.swing.GroupLayout(options_Panel);
        options_Panel.setLayout(options_PanelLayout);
        options_PanelLayout.setHorizontalGroup(
                options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(options_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bankOre_CheckBox)
                                .addGap(41, 41, 41)
                                .addComponent(upgradePickaxe_CheckBox)
                                .addGap(29, 29, 29)
                                .addComponent(autoHop_CheckBox)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        options_PanelLayout.setVerticalGroup(
                options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(options_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankOre_CheckBox)
                                        .addComponent(upgradePickaxe_CheckBox)
                                        .addComponent(autoHop_CheckBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(options_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(title_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(rockArea_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(loadTilles_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(bankArea_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(rockName_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title_Lbl)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bankArea_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(rockName_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(rockArea_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(loadTilles_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(options_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void rockAreaTL_TxtBoxFocusGained(FocusEvent evt) {
        if (rockAreaTL_TxtBox.getText().trim().equals("Top Left Tile"))
            rockAreaTL_TxtBox.setText("");
    }

    private void rockAreaTL_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (rockAreaTL_TxtBox.getText().trim().equals(""))
            rockAreaTL_TxtBox.setText("Top Left Tile");
    }

    private void rockAreaTL_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            rockAreaTL_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void rockAreaBR_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (rockAreaBR_TxtBox.getText().trim().equals("Bottom Right"))
            rockAreaBR_TxtBox.setText("");
    }

    private void rockAreaBR_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (rockAreaBR_TxtBox.getText().trim().equals(""))
            rockAreaBR_TxtBox.setText("Bottom Right");
    }

    private void rockAreaBR_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            rockAreaBR_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankAreaTL_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (bankAreaTL_TxtBox.getText().trim().equals("Top Left Tile"))
            bankAreaTL_TxtBox.setText("");
    }

    private void bankAreaTL_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (bankAreaTL_TxtBox.getText().trim().equals(""))
            bankAreaTL_TxtBox.setText("Top Left Tile");
    }

    private void bankAreaTL_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            bankAreaTL_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankAreaBR_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (bankAreaBR_TxtBox.getText().trim().equals("Bottom Right"))
            bankAreaBR_TxtBox.setText("");
    }

    private void bankAreaBR_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (bankAreaBR_TxtBox.getText().trim().equals(""))
            bankAreaBR_TxtBox.setText("Bottom Right");
    }

    private void bankAreaBR_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            bankAreaBR_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankTile_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (bankTile_TxtBox.getText().trim().equals("Centre Tile"))
            bankTile_TxtBox.setText("");
    }

    private void bankTile_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (bankTile_TxtBox.getText().trim().equals(""))
            bankTile_TxtBox.setText("Centre Tile");
    }

    private void bankTile_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            bankTile_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankOre_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {
        if (bankOre_CheckBox.isSelected()) {
            bankArea_Panel.setEnabled(true);

            bankAreaTL_TxtBox.setEnabled(true);
            bankAreaTL_Btn.setEnabled(true);

            bankAreaBR_TxtBox.setEnabled(true);
            bankAreaBR_Btn.setEnabled(true);

            bankTile_TxtBox.setEnabled(true);
            bankTile_Btn.setEnabled(true);

            upgradePickaxe_CheckBox.setEnabled(true);

        }else{
            bankArea_Panel.setEnabled(false);

            bankAreaTL_TxtBox.setEnabled(false);
            bankAreaTL_Btn.setEnabled(false);

            bankAreaBR_TxtBox.setEnabled(false);
            bankAreaBR_Btn.setEnabled(false);

            bankTile_TxtBox.setEnabled(false);
            bankTile_Btn.setEnabled(false);

            upgradePickaxe_CheckBox.setSelected(false);
            upgradePickaxe_CheckBox.setEnabled(false);

        }
    }



    private void dataString_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (dataString_TxtBox.getText().trim().equals("GUI Data String"))
            dataString_TxtBox.setText("");
    }

    private void dataString_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (dataString_TxtBox.getText().trim().equals(""))
            dataString_TxtBox.setText("GUI Data String");
    }

    private String Separator = "#";
    private void loadData_BtnActionPerformed(java.awt.event.ActionEvent evt) {

        JCheckBox[] allCheckBox = {bankOre_CheckBox, autoHop_CheckBox, upgradePickaxe_CheckBox};
        JTextField[] allTileInputs = {rockAreaTL_TxtBox, rockAreaBR_TxtBox, bankAreaTL_TxtBox, bankAreaBR_TxtBox, bankTile_TxtBox};

        Clipboard c = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable t = c.getContents(this);
        if (t != null) {
            try {
                String clipboardText = (String) t.getTransferData(DataFlavor.stringFlavor);
                if (dataString_TxtBox.getText().split(Separator).length != 9 && clipboardText.split(Separator).length == 9)
                    dataString_TxtBox.setText(clipboardText);
            } catch (Exception e){}
        }

        try {

            String[] rawData = dataString_TxtBox.getText().split(Separator);
            if (rawData.length == 9) {
                int rawDataCount = 0;
                for (int checkBoxCount = 0; checkBoxCount < allCheckBox.length; checkBoxCount++, rawDataCount++) {
                    if (rawData[rawDataCount].equals("t"))
                        allCheckBox[checkBoxCount].setSelected(true);
                    else
                        allCheckBox[checkBoxCount].setSelected(false);
                }

                for (int tileCount = 0; tileCount < allTileInputs.length; tileCount++, rawDataCount++)
                    allTileInputs[tileCount].setText(rawData[rawDataCount]);

                rockIDs_TxtBox.setText(rawData[rawDataCount]);

            }else{
                System.out.println("Invalid GUI Data String");
            }
        }catch (Exception e){
            System.out.println("Invalid GUI Data String");
        }
    }

    private void generateData_BtnActionPerformed(java.awt.event.ActionEvent evt) {

        String output = "";
        JCheckBox[] allCheckBox = {bankOre_CheckBox, autoHop_CheckBox, upgradePickaxe_CheckBox};
        for (int i = 0; i < allCheckBox.length; i++){
            if (allCheckBox[i].isSelected())
                output = output + "t" + Separator;
            else
                output = output + "f" + Separator;
        }

        JTextField[] allTileInputs = {rockAreaTL_TxtBox, rockAreaBR_TxtBox, bankAreaTL_TxtBox, bankAreaBR_TxtBox, bankTile_TxtBox};
        for (int i = 0; i <allTileInputs.length; i++)
            output = output + allTileInputs[i].getText() + Separator;

        output = output + rockIDs_TxtBox.getText();

        dataString_TxtBox.setText(output);

        StringSelection stringSelection = new StringSelection(output);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }



    private void start_BtnActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            AIO_Miner.rockArea = new RSArea(parseRSTile(rockAreaTL_TxtBox.getText()), parseRSTile(rockAreaBR_TxtBox.getText()));
            if (bankOre_CheckBox.isSelected()) {
                AIO_Miner.bankArea = new RSArea(parseRSTile(bankAreaTL_TxtBox.getText()), parseRSTile(bankAreaBR_TxtBox.getText()));
                AIO_Miner.bankTile = parseRSTile(bankTile_TxtBox.getText());
            }

            String[] stringRockIDs = rockIDs_TxtBox.getText().split(",");
            int[] intRockIDs = new int[stringRockIDs.length];
            for (int i = 0; i < stringRockIDs.length; i++)
                intRockIDs[i] = Integer.parseInt(stringRockIDs[i].trim());

            AIO_Miner.rockIDs = intRockIDs;
            AIO_Miner.autoHop = autoHop_CheckBox.isSelected();
            AIO_Miner.autoUpgradePickaxe = upgradePickaxe_CheckBox.isSelected();
            AIO_Miner.bankOre = bankOre_CheckBox.isSelected();

            setVisible(false);
            guiCompleted = true;

        }catch (Exception e){
            System.out.println("Input Error, please make sure all tiles are inputted correctly.");
        }
    }

    private RSTile parseRSTile(String input){

        String[] rawTile = input.replace('(', ' ').replace(", 0)", "").trim().split(",");
        return new RSTile(Integer.parseInt(rawTile[0].trim()), Integer.parseInt(rawTile[1].trim()));

    }




    // Variables declaration - do not modify
    private javax.swing.JCheckBox autoHop_CheckBox;
    private javax.swing.JButton bankAreaBR_Btn;
    private javax.swing.JTextField bankAreaBR_TxtBox;
    private javax.swing.JButton bankAreaTL_Btn;
    private javax.swing.JTextField bankAreaTL_TxtBox;
    private javax.swing.JPanel bankArea_Panel;
    private javax.swing.JCheckBox bankOre_CheckBox;
    private javax.swing.JButton bankTile_Btn;
    private javax.swing.JTextField bankTile_TxtBox;
    private javax.swing.JTextField dataString_TxtBox;
    private javax.swing.JButton generateData_Btn;
    private javax.swing.JButton loadData_Btn;
    private javax.swing.JPanel loadTilles_Panel;
    private javax.swing.JPanel options_Panel;
    private javax.swing.JButton rockAreaBR_Btn;
    private javax.swing.JTextField rockAreaBR_TxtBox;
    private javax.swing.JButton rockAreaTL_Btn;
    private javax.swing.JTextField rockAreaTL_TxtBox;
    private javax.swing.JPanel rockArea_Panel;
    private javax.swing.JTextField rockIDs_TxtBox;
    private javax.swing.JPanel rockName_Panel;
    private javax.swing.JButton start_Btn;
    private javax.swing.JLabel title_Lbl;
    private javax.swing.JCheckBox upgradePickaxe_CheckBox;
    // End of variables declaration
}

