package scripts.Woodcutter;

import org.tribot.api2007.Game;
import org.tribot.api2007.Login;
import org.tribot.api2007.Player;
import org.tribot.api2007.types.RSArea;
import org.tribot.api2007.types.RSTile;

import javax.swing.*;
import java.awt.*;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

/**
 *
 * @author James
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public boolean guiCompleted = false;

    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("Z3D's AIO Woodcutter");

        title_Lbl = new javax.swing.JLabel();
        treeArea_Panel = new javax.swing.JPanel();
        treeAreaTL_TxtBox = new javax.swing.JTextField();
        treeAreaBR_TxtBox = new javax.swing.JTextField();
        treeAreaTL_Btn = new javax.swing.JButton();
        treeAreaBR_Btn = new javax.swing.JButton();
        bankArea_Panel = new javax.swing.JPanel();
        bankAreaTL_TxtBox = new javax.swing.JTextField();
        bankAreaBR_TxtBox = new javax.swing.JTextField();
        bankAreaTL_Btn = new javax.swing.JButton();
        bankAreaBR_Btn = new javax.swing.JButton();
        bankTile_TxtBox = new javax.swing.JTextField();
        bankTile_Btn = new javax.swing.JButton();
        loadTilles_Panel = new javax.swing.JPanel();
        dataString_TxtBox = new javax.swing.JTextField();
        generateData_Btn = new javax.swing.JButton();
        loadData_Btn = new javax.swing.JButton();
        start_Btn = new javax.swing.JButton();
        treeName_Panel = new javax.swing.JPanel();
        treeName_Dropdown = new javax.swing.JComboBox();
        options_Panel = new javax.swing.JPanel();
        bankLogs_CheckBox = new javax.swing.JCheckBox();
        upgradeAxe_CheckBox = new javax.swing.JCheckBox();
        hoverLastChopped_CheckBox = new javax.swing.JCheckBox();

        title_Lbl.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        title_Lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title_Lbl.setText("Z3D's AIO Woodcutter");

        treeArea_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tree Area"));
        treeArea_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeArea_Panel.setName("Tree Area"); // NOI18N

        treeAreaTL_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeAreaTL_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        treeAreaTL_TxtBox.setText("Top Left Tile");
        treeAreaTL_TxtBox.setToolTipText("The top left tile in the area in the format: 3897, 1089");
        treeAreaTL_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                treeAreaTL_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                treeAreaTL_TxtBoxFocusLost(evt);
            }
        });

        treeAreaBR_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeAreaBR_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        treeAreaBR_TxtBox.setText("Bottom Right");
        treeAreaBR_TxtBox.setToolTipText("The bottom right tile in the area in the format: 3897, 1089");
        treeAreaBR_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                treeAreaBR_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                treeAreaBR_TxtBoxFocusLost(evt);
            }
        });

        treeAreaTL_Btn.setBackground(new java.awt.Color(255, 228, 255));
        treeAreaTL_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeAreaTL_Btn.setText("Grab Tile");
        treeAreaTL_Btn.setToolTipText("Grabs the current tile you're standing on");
        treeAreaTL_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeAreaTL_BtnActionPerformed(evt);
            }
        });

        treeAreaBR_Btn.setBackground(new java.awt.Color(255, 228, 255));
        treeAreaBR_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeAreaBR_Btn.setText("Grab Tile");
        treeAreaBR_Btn.setToolTipText("Grabs the current tile you're standing on");
        treeAreaBR_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeAreaBR_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout treeArea_PanelLayout = new javax.swing.GroupLayout(treeArea_Panel);
        treeArea_Panel.setLayout(treeArea_PanelLayout);
        treeArea_PanelLayout.setHorizontalGroup(
                treeArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(treeArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(treeArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(treeArea_PanelLayout.createSequentialGroup()
                                                .addComponent(treeAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(treeAreaTL_Btn))
                                        .addGroup(treeArea_PanelLayout.createSequentialGroup()
                                                .addComponent(treeAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(treeAreaBR_Btn)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        treeArea_PanelLayout.setVerticalGroup(
                treeArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(treeArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(treeArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(treeAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(treeAreaTL_Btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(treeArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(treeAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(treeAreaBR_Btn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bankArea_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Bank Area"));
        bankArea_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankArea_Panel.setName("Tree Area"); // NOI18N

        bankAreaTL_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaTL_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankAreaTL_TxtBox.setText("Top Left Tile");
        bankAreaTL_TxtBox.setToolTipText("The top left tile in the area in the format: 3897, 1089");
        bankAreaTL_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankAreaTL_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAreaTL_TxtBoxFocusLost(evt);
            }
        });

        bankAreaBR_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaBR_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankAreaBR_TxtBox.setText("Bottom Right");
        bankAreaBR_TxtBox.setToolTipText("The bottom right tile in the area in the format: 3897, 1089");
        bankAreaBR_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankAreaBR_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankAreaBR_TxtBoxFocusLost(evt);
            }
        });

        bankAreaTL_Btn.setBackground(new java.awt.Color(255, 228, 255));
        bankAreaTL_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaTL_Btn.setText("Grab Tile");
        bankAreaTL_Btn.setToolTipText("Grabs the current tile you're standing on");
        bankAreaTL_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankAreaTL_BtnActionPerformed(evt);
            }
        });

        bankAreaBR_Btn.setBackground(new java.awt.Color(255, 228, 255));
        bankAreaBR_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankAreaBR_Btn.setText("Grab Tile");
        bankAreaBR_Btn.setToolTipText("Grabs the current tile you're standing on");
        bankAreaBR_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankAreaBR_BtnActionPerformed(evt);
            }
        });

        bankTile_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankTile_TxtBox.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bankTile_TxtBox.setText("Centre Tile");
        bankTile_TxtBox.setToolTipText("A tile closest to the bank booth");
        bankTile_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                bankTile_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                bankTile_TxtBoxFocusLost(evt);
            }
        });

        bankTile_Btn.setBackground(new java.awt.Color(255, 228, 255));
        bankTile_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankTile_Btn.setText("Grab Tile");
        bankTile_Btn.setToolTipText("Grabs the current tile you're standing on");
        bankTile_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankTile_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bankArea_PanelLayout = new javax.swing.GroupLayout(bankArea_Panel);
        bankArea_Panel.setLayout(bankArea_PanelLayout);
        bankArea_PanelLayout.setHorizontalGroup(
                bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                                .addComponent(bankAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bankAreaTL_Btn))
                                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                                .addComponent(bankAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bankAreaBR_Btn))
                                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                                .addComponent(bankTile_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(bankTile_Btn)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );
        bankArea_PanelLayout.setVerticalGroup(
                bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(bankArea_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankAreaTL_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bankAreaTL_Btn))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankAreaBR_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bankAreaBR_Btn))
                                .addGap(18, 18, 18)
                                .addGroup(bankArea_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankTile_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bankTile_Btn))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        loadTilles_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Load Tiles"));
        loadTilles_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loadTilles_Panel.setName("Tree Area"); // NOI18N

        dataString_TxtBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        dataString_TxtBox.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dataString_TxtBox.setText("GUI Data String");
        dataString_TxtBox.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                dataString_TxtBoxFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                dataString_TxtBoxFocusLost(evt);
            }
        });

        generateData_Btn.setBackground(new java.awt.Color(255, 228, 255));
        generateData_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        generateData_Btn.setText("Generate");
        generateData_Btn.setToolTipText("Generates a GUI data string");
        generateData_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generateData_BtnActionPerformed(evt);
            }
        });

        loadData_Btn.setBackground(new java.awt.Color(255, 228, 255));
        loadData_Btn.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        loadData_Btn.setText("Load");
        loadData_Btn.setToolTipText("Loads all GUI data from the Data String");
        loadData_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadData_BtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadTilles_PanelLayout = new javax.swing.GroupLayout(loadTilles_Panel);
        loadTilles_Panel.setLayout(loadTilles_PanelLayout);
        loadTilles_PanelLayout.setHorizontalGroup(
                loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loadTilles_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dataString_TxtBox)
                                        .addGroup(loadTilles_PanelLayout.createSequentialGroup()
                                                .addComponent(loadData_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(18, 18, 18)
                                                .addComponent(generateData_Btn)))
                                .addContainerGap())
        );
        loadTilles_PanelLayout.setVerticalGroup(
                loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(loadTilles_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(dataString_TxtBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(loadTilles_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(loadData_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(generateData_Btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );

        start_Btn.setBackground(new java.awt.Color(231, 234, 183));
        start_Btn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        start_Btn.setText("Start");
        start_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_BtnActionPerformed(evt);
            }
        });

        treeName_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Tree Name"));
        treeName_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeName_Panel.setName("Tree Area"); // NOI18N

        treeName_Dropdown.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        treeName_Dropdown.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tree", "Achey", "Oak", "Willow", "Teak", "Maple", "Mahogany", "Arctic pine", "Yew", "Magic tree", "Redwood" }));

        javax.swing.GroupLayout treeName_PanelLayout = new javax.swing.GroupLayout(treeName_Panel);
        treeName_Panel.setLayout(treeName_PanelLayout);
        treeName_PanelLayout.setHorizontalGroup(
                treeName_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(treeName_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(treeName_Dropdown, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        treeName_PanelLayout.setVerticalGroup(
                treeName_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(treeName_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(treeName_Dropdown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        options_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Other Options"));
        options_Panel.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        options_Panel.setName("Tree Area"); // NOI18N

        bankLogs_CheckBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        bankLogs_CheckBox.setSelected(true);
        bankLogs_CheckBox.setText("Bank Logs");
        bankLogs_CheckBox.setToolTipText("If not checked will drop logs");
        bankLogs_CheckBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                bankLogs_CheckBoxItemStateChanged(evt);
            }
        });

        upgradeAxe_CheckBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        upgradeAxe_CheckBox.setSelected(true);
        upgradeAxe_CheckBox.setText("Auto Upgrade Axe");
        upgradeAxe_CheckBox.setToolTipText("Will automatically get the best axe from your bank and use that");

        hoverLastChopped_CheckBox.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        hoverLastChopped_CheckBox.setSelected(true);
        hoverLastChopped_CheckBox.setText("Hover Last Chopped Tree");
        hoverLastChopped_CheckBox.setToolTipText("Hover over the last tree chopped instead of the next valid tree");

        javax.swing.GroupLayout options_PanelLayout = new javax.swing.GroupLayout(options_Panel);
        options_Panel.setLayout(options_PanelLayout);
        options_PanelLayout.setHorizontalGroup(
                options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(options_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bankLogs_CheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(upgradeAxe_CheckBox)
                                .addGap(18, 18, 18)
                                .addComponent(hoverLastChopped_CheckBox)
                                .addContainerGap(13, Short.MAX_VALUE))
        );
        options_PanelLayout.setVerticalGroup(
                options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(options_PanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(options_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bankLogs_CheckBox)
                                        .addComponent(upgradeAxe_CheckBox)
                                        .addComponent(hoverLastChopped_CheckBox))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(156, 156, 156))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(title_Lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(options_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(treeArea_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(loadTilles_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                        .addComponent(bankArea_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(treeName_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(title_Lbl)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(bankArea_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(treeName_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(treeArea_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(loadTilles_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(options_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(start_Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>


    private void treeAreaTL_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (treeAreaTL_TxtBox.getText().trim().equals("Top Left Tile"))
            treeAreaTL_TxtBox.setText("");
    }

    private void treeAreaTL_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (treeAreaTL_TxtBox.getText().trim().equals(""))
            treeAreaTL_TxtBox.setText("Top Left Tile");
    }

    private void treeAreaTL_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            treeAreaTL_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void treeAreaBR_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (treeAreaBR_TxtBox.getText().trim().equals("Bottom Right"))
            treeAreaBR_TxtBox.setText("");
    }

    private void treeAreaBR_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (treeAreaBR_TxtBox.getText().trim().equals(""))
            treeAreaBR_TxtBox.setText("Bottom Right");
    }

    private void treeAreaBR_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            treeAreaBR_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankAreaTL_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (bankAreaTL_TxtBox.getText().trim().equals("Top Left Tile"))
            bankAreaTL_TxtBox.setText("");
    }

    private void bankAreaTL_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (bankAreaTL_TxtBox.getText().trim().equals(""))
            bankAreaTL_TxtBox.setText("Top Left Tile");
    }

    private void bankAreaTL_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            bankAreaTL_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankAreaBR_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (bankAreaBR_TxtBox.getText().trim().equals("Bottom Right"))
            bankAreaBR_TxtBox.setText("");
    }

    private void bankAreaBR_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (bankAreaBR_TxtBox.getText().trim().equals(""))
            bankAreaBR_TxtBox.setText("Bottom Right");
    }

    private void bankAreaBR_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            bankAreaBR_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankTile_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (bankTile_TxtBox.getText().trim().equals("Centre Tile"))
            bankTile_TxtBox.setText("");
    }

    private void bankTile_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (bankTile_TxtBox.getText().trim().equals(""))
            bankTile_TxtBox.setText("Centre Tile");
    }

    private void bankTile_BtnActionPerformed(java.awt.event.ActionEvent evt) {
        if (Player.getPosition() != null){
            bankTile_TxtBox.setText(Player.getPosition().toString().replace('(', ' ').replace(", 0)", "").trim());
        }else{
            System.out.println("Could not find the tile you're on!");
        }
    }



    private void bankLogs_CheckBoxItemStateChanged(java.awt.event.ItemEvent evt) {
        if (bankLogs_CheckBox.isSelected()) {
            bankArea_Panel.setEnabled(true);

            bankAreaTL_TxtBox.setEnabled(true);
            bankAreaTL_Btn.setEnabled(true);

            bankAreaBR_TxtBox.setEnabled(true);
            bankAreaBR_Btn.setEnabled(true);

            bankTile_TxtBox.setEnabled(true);
            bankTile_Btn.setEnabled(true);

            upgradeAxe_CheckBox.setEnabled(true);

        }else{
            bankArea_Panel.setEnabled(false);

            bankAreaTL_TxtBox.setEnabled(false);
            bankAreaTL_Btn.setEnabled(false);

            bankAreaBR_TxtBox.setEnabled(false);
            bankAreaBR_Btn.setEnabled(false);

            bankTile_TxtBox.setEnabled(false);
            bankTile_Btn.setEnabled(false);

            upgradeAxe_CheckBox.setSelected(false);
            upgradeAxe_CheckBox.setEnabled(false);

        }
    }



    private void dataString_TxtBoxFocusGained(java.awt.event.FocusEvent evt) {
        if (dataString_TxtBox.getText().trim().equals("GUI Data String"))
            dataString_TxtBox.setText("");
    }

    private void dataString_TxtBoxFocusLost(java.awt.event.FocusEvent evt) {
        if (dataString_TxtBox.getText().trim().equals(""))
            dataString_TxtBox.setText("GUI Data String");
    }

    private String Separator = "#";
    private void loadData_BtnActionPerformed(java.awt.event.ActionEvent evt) {

        JCheckBox[] allCheckBox = {bankLogs_CheckBox, hoverLastChopped_CheckBox, upgradeAxe_CheckBox};
        JTextField[] allTileInputs = {treeAreaTL_TxtBox, treeAreaBR_TxtBox, bankAreaTL_TxtBox, bankAreaBR_TxtBox, bankTile_TxtBox};

        Clipboard c = Toolkit.getDefaultToolkit().getSystemClipboard();
        Transferable t = c.getContents(this);
        if (t != null) {
            try {
                String clipboardText = (String) t.getTransferData(DataFlavor.stringFlavor);
                if (dataString_TxtBox.getText().split(Separator).length != 9 && clipboardText.split(Separator).length == 9)
                    dataString_TxtBox.setText(clipboardText);
            } catch (Exception e){}
        }

        try {

            String[] rawData = dataString_TxtBox.getText().split(Separator);
            if (rawData.length == 9) {
                int rawDataCount = 0;
                for (int checkBoxCount = 0; checkBoxCount < allCheckBox.length; checkBoxCount++, rawDataCount++) {
                    if (rawData[rawDataCount].equals("t"))
                        allCheckBox[checkBoxCount].setSelected(true);
                    else
                        allCheckBox[checkBoxCount].setSelected(false);
                }

                for (int tileCount = 0; tileCount < allTileInputs.length; tileCount++, rawDataCount++)
                    allTileInputs[tileCount].setText(rawData[rawDataCount]);

                treeName_Dropdown.setSelectedIndex(Integer.parseInt(rawData[rawDataCount]));
            }else{
                System.out.println("Invalid GUI Data String");
            }
        }catch (Exception e){
            System.out.println("Invalid GUI Data String");
        }
    }

    private void generateData_BtnActionPerformed(java.awt.event.ActionEvent evt) {

        String output = "";
        JCheckBox[] allCheckBox = {bankLogs_CheckBox, hoverLastChopped_CheckBox, upgradeAxe_CheckBox};
        for (int i = 0; i < allCheckBox.length; i++){
            if (allCheckBox[i].isSelected())
                output = output + "t" + Separator;
            else
                output = output + "f" + Separator;
        }

        JTextField[] allTileInputs = {treeAreaTL_TxtBox, treeAreaBR_TxtBox, bankAreaTL_TxtBox, bankAreaBR_TxtBox, bankTile_TxtBox};
        for (int i = 0; i <allTileInputs.length; i++)
            output = output + allTileInputs[i].getText() + Separator;

        output = output + treeName_Dropdown.getSelectedIndex();

        dataString_TxtBox.setText(output);

        StringSelection stringSelection = new StringSelection(output);
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);
    }



    private void start_BtnActionPerformed(java.awt.event.ActionEvent evt) {

        try {
            AIO_Woodcutter.TREE_AREA = new RSArea(parseRSTile(treeAreaTL_TxtBox.getText()), parseRSTile(treeAreaBR_TxtBox.getText()));
            if (bankLogs_CheckBox.isSelected()) {
                AIO_Woodcutter.BANK_AREA = new RSArea(parseRSTile(bankAreaTL_TxtBox.getText()), parseRSTile(bankAreaBR_TxtBox.getText()));
                AIO_Woodcutter.BANK_TILE = parseRSTile(bankTile_TxtBox.getText());
            }

            AIO_Woodcutter.TREE_NAME = treeName_Dropdown.getSelectedItem().toString();
            AIO_Woodcutter.autoUpgradeAxe = upgradeAxe_CheckBox.isSelected();
            AIO_Woodcutter.hoverOverLastChopped = hoverLastChopped_CheckBox.isSelected();
            AIO_Woodcutter.bankLogs = bankLogs_CheckBox.isSelected();

            setVisible(false);
            guiCompleted = true;

        }catch (Exception e){
            System.out.println("Input Error, please make sure all tiles are inputted correctly.");
        }
    }

    private RSTile parseRSTile(String input){

        String[] rawTile = input.replace('(', ' ').replace(", 0)", "").trim().split(",");
        return new RSTile(Integer.parseInt(rawTile[0].trim()), Integer.parseInt(rawTile[1].trim()));

    }



    // Variables declaration - do not modify
    private javax.swing.JButton bankAreaBR_Btn;
    private javax.swing.JTextField bankAreaBR_TxtBox;
    private javax.swing.JButton bankAreaTL_Btn;
    private javax.swing.JTextField bankAreaTL_TxtBox;
    private javax.swing.JPanel bankArea_Panel;
    private javax.swing.JCheckBox bankLogs_CheckBox;
    private javax.swing.JButton bankTile_Btn;
    private javax.swing.JTextField bankTile_TxtBox;
    private javax.swing.JTextField dataString_TxtBox;
    private javax.swing.JButton generateData_Btn;
    private javax.swing.JCheckBox hoverLastChopped_CheckBox;
    private javax.swing.JButton loadData_Btn;
    private javax.swing.JPanel loadTilles_Panel;
    private javax.swing.JPanel options_Panel;
    private javax.swing.JButton start_Btn;
    private javax.swing.JLabel title_Lbl;
    private javax.swing.JButton treeAreaBR_Btn;
    private javax.swing.JTextField treeAreaBR_TxtBox;
    private javax.swing.JButton treeAreaTL_Btn;
    private javax.swing.JTextField treeAreaTL_TxtBox;
    private javax.swing.JPanel treeArea_Panel;
    private javax.swing.JComboBox<String> treeName_Dropdown;
    private javax.swing.JPanel treeName_Panel;
    private javax.swing.JCheckBox upgradeAxe_CheckBox;
    // End of variables declaration
}

